/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommonAside: typeof import('./src/components/CommonAside.vue')['default']
    CommonHeader: typeof import('./src/components/CommonHeader.vue')['default']
    DAside: typeof import('vue-devui/layout/index.es.js')['Aside']
    DButton: typeof import('vue-devui/button/index.es.js')['Button']
    DContent: typeof import('vue-devui/layout/index.es.js')['Content']
    DFooter: typeof import('vue-devui/layout/index.es.js')['Footer']
    DHeader: typeof import('vue-devui/layout/index.es.js')['Header']
    DLayout: typeof import('vue-devui/layout/index.es.js')['Layout']
    MainLobby: typeof import('./src/components/MainLobby.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
